---

- hosts: all
  sudo: true
  tasks:

    - name: install epel so I can get needed libraries
      yum: name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
           state=present

    - name: install icinga dependencies
      yum: name=php,php-cli,php-pear,php-xmlrpc,php-xsl,php-pdo,php-soap,php-gd,php-ldap,php-mysql,mysql-server,mysql-devel
           state=present

    - name: install java for lein
      yum: name=java-1.7.0-openjdk,java-1.7.0-openjdk-devel
           state=present

    # ignoring certs since github doesn't match rawdata.github
    - name: download lein script.
      command: wget -O /usr/bin/lein --no-clobber --no-check-certificate https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
               creates=/usr/bin/lein

    - name: set permissions on lein
      file: mode=755 dest=/usr/bin/lein

    - name: install lein
      shell: yes | /usr/bin/lein

    - name: install repoforge to install icinga
      yum: name=http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
           state=present

    - name: install icinga
      yum: name=icinga-web,icinga,icinga-idoutils-libdbi-mysql
           state=present

    - name: install python-devel and pip for mysql-python later
      yum: name=python-devel,python-pip
           state=present

    - name: install python mysqldb module for mysql setup
      pip: name=mysql-python
           state=present

    - name: stop iptables for external access to ports
      service: name=iptables
               state=stopped
               enabled=no

    - name: start mysql
      service: name=mysqld
               state=started
               enabled=yes

    - name: start httpd
      service: name=httpd
               state=started
               enabled=yes

    - name: start icinga
      service: name=icinga
               state=started
               enabled=yes

    - name: start ido
      service: name=ido2db
               state=started
               enabled=yes

    - name: create icinga database
      mysql_db: name=icinga

    - name: create icinga_web mysql user
      mysql_user: user=icinga
                  password=icinga
                  state=present
                  priv=icinga.*:all

    - name: set up the icinga ido thingy
      shell: mysql icinga -u icinga -picinga < /usr/share/doc/icinga-idoutils-libdbi-mysql-1.8.4/db/mysql/mysql.sql && touch /etc/icinga/db-loaded.txt
             creates=/etc/icinga/db-loaded.txt

    - name: create icinga_web database
      mysql_db: name=icinga_web

    - name: create icinga_web mysql user
      mysql_user: user=icinga_web
                  password=icinga_web
                  state=present
                  priv=icinga_web.*:all

    - name: load the icinga_web schema
      shell: mysql -u root icinga_web < /usr/share/doc/icinga-web-1.7.2/schema/mysql.sql && touch /etc/icinga-web/db_loaded.done
             creates=/etc/icinga-web/db_loaded.done

- hosts: all
  tasks:
   - name: make the clj-ssh.cli library happy by creating a known_hosts file
     command: touch ~/.ssh/known_hosts
